name: ipagpt_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu126
      - torch==2.10.0.dev20250927+cu126

      - tokenizers>=0.22
      - datasets>=4.2
      - huggingface-hub>=0.35
      - numpy>=2.2
      - scipy>=1.15
      - scikit-learn>=1.7
      - pandas>=2.3
      - pyarrow>=21
      - tqdm>=4.67
      - requests>=2.32
      - aiohttp>=3.13
      - fsspec>=2024.3
      - pyyaml>=6
      - wandb>=0.22
      - transformers>=4.57
      - sentence-transformers>=5.0
      - tiktoken>=0.5
      - einops>=0.6
      - safetensors>=0.4
      - pillow>=10
      - psutil>=5.9
      - regex>=2024.5.15
      - simple-parsing>=0.1.7
      - docstring_parser>=0.17
      - tensorflow-datasets>=4.9    
      - tensorflow-metadata>=1.17   
      - vega-datasets>=0.9
      - importlib_resources>=6.4    
      - zipp>=3.19
      # older deps
      - array_record>=0.8
      - etils>=1.5
      - immutabledict>=4.1